'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import type {Locale} from '../content';
type Message={role:'user'|'assistant';content:string;routes?:string[]};
const allowed=['services#technology','services#marketing','products','work','about','contact'];
export function WelcomeChat({locale}:{locale:Locale}){
 const ar=locale==='ar';const [open,setOpen]=useState(false),[messages,setMessages]=useState<Message[]>([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const field=useRef<HTMLInputElement>(null),launcher=useRef<HTMLButtonElement>(null),scroll=useRef<HTMLDivElement>(null),panel=useRef<HTMLElement>(null),controller=useRef<AbortController|null>(null);
 const labels=ar?['التكنولوجيا والبرمجة','التسويق الرقمي','منتجاتنا','أعمالنا','عن الشركة','ملخص المشروع']:['Technology & development','Digital marketing','Our products','Client work','About INDOM','Project brief'];
 useEffect(()=>{if(new URLSearchParams(window.location.search).get('welcome')==='1')setOpen(true);return()=>controller.current?.abort()},[]);
 useEffect(()=>{if(!open)return;field.current?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);launcher.current?.focus()}if(e.key==='Tab'){const nodes=panel.current?.querySelectorAll<HTMLElement>('button:not(:disabled),a,input');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[open]);
 useEffect(()=>{scroll.current?.scrollTo({top:scroll.current.scrollHeight,behavior:'auto'})},[messages,busy]);
 async function send(value:string){if(busy||!value.trim())return;const next:Message[]=[...messages,{role:'user',content:value.trim().slice(0,800)}];setMessages(next);setInput('');setError('');setBusy(true);const abort=new AbortController();controller.current=abort;
 try{const response=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({locale,messages:next.slice(-7).map(({role,content})=>({role,content:content.slice(0,1200)}))}),signal:abort.signal});const data=await response.json();if(!response.ok)throw Error(data.error||'');setMessages([...next,{role:'assistant',content:data.answer,routes:(data.routes||[]).filter((x:string)=>allowed.includes(x))}]);}
 catch(e){if(!abort.signal.aborted)setError(e instanceof Error&&e.message&&!e.message.includes('fetch')?e.message:(ar?'تعذر الاتصال. حاول مجددًا أو استخدم روابط الخدمات.':'Unable to connect. Try again or use the service links.'));}finally{if(!abort.signal.aborted)setBusy(false)}
 }
 function close(){setOpen(false);launcher.current?.focus()}
 return <><button className="welcome-launcher" ref={launcher} onClick={()=>setOpen(v=>!v)} aria-expanded={open} aria-controls="welcome-chat">{ar?'مرحبًا':'Welcome'}</button>{open&&<div className="chat-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section ref={panel} id="welcome-chat" className="welcome-panel" role="dialog" aria-modal="true" aria-label={ar?'مساعد INDOM':'INDOM assistant'}><header><div><strong>{ar?'مساعد INDOM':'INDOM assistant'}</strong><p>{ar?'كيف يمكننا مساعدتك؟':'How can we help?'}</p></div><button onClick={close} aria-label={ar?'إغلاق':'Close'}>×</button></header><div className="chat-scroll" ref={scroll} role="log" aria-live="polite" aria-label={ar?"المحادثة":"Conversation"}><p className="chat-greeting">{ar?'مرحبًا! اسأل عن خدماتنا أو منتجاتنا، وسأوجهك إلى الصفحة المناسبة.':'Welcome! Ask about our services or products and I’ll guide you to the right page.'}</p><div className="chat-quick">{[ar?'أحتاج تطوير موقع':'I need a website',ar?'أحتاج تسويق وسوشيال ميديا':'I need marketing and social media'].map(q=><button key={q} disabled={busy} onClick={()=>send(q)}>{q}</button>)}</div>{messages.map((message,i)=><article className={`chat-message ${message.role}`} key={i}><span>{message.role==='user'?(ar?'أنت':'You'):(ar?'المساعد':'Assistant')}</span><p>{message.content}</p>{message.routes&&<div className="chat-routes">{message.routes.map(path=><Link href={`/${locale}/${path}`} onClick={close} key={path}>{labels[allowed.indexOf(path)]} ↗</Link>)}</div>}</article>)}{busy&&<p role="status">{ar?'جارٍ إعداد الإجابة…':'Preparing a reply…'}</p>}{error&&<p role="alert">{error}</p>}</div><form onSubmit={e=>{e.preventDefault();send(input)}} className="chat-form"><label className="sr-only" htmlFor="chat-question">{ar?'سؤالك':'Your question'}</label><input id="chat-question" ref={field} value={input} onChange={e=>setInput(e.target.value)} maxLength={800} placeholder={ar?'اكتب سؤالك…':'Ask a question…'} autoComplete="off" required/><button type="submit" disabled={busy||!input.trim()}>{ar?'إرسال':'Send'}</button></form><div className="chat-footer"><Link href={`/${locale}/privacy`} onClick={close}>{ar?'الخصوصية':'Privacy'}</Link><button disabled={busy} onClick={()=>{setMessages([]);setError('');field.current?.focus()}}>{ar?'مسح المحادثة':'Clear conversation'}</button></div><p className="chat-notice">{ar?'تُعالج الرسائل لتوليد الإجابة. لا تشارك بيانات حساسة.':'Messages are processed to generate replies. Avoid sensitive information.'}</p></section></div>}</>;
}
